### ISSUE TITLE
Run eShop on containers project in Docker

### ISSUE THREAD

**Issue by kct949** [otter-diku/simulation-framework-for-microservices#2]

**Comment by PTheyssen** [comment]
Currently have problem with login side for MVC frontend getting:

InvalidOperationException: IDX20803: Unable to obtain configuration from: 'http://docker.for.linux.localhost:5105/.well-known/openid-configuration'.

For now ignore this and only investigate further if we need this to work for workload generation

**Comment by kct949** [comment]
I ran the eshop and AFAIR it worked fine, but I did not explore all the paths to make sure everything works. Can be closed for now IMO
